In [1]:
import numpy as np
np.random.seed(42) #Don't change the seed

In [2]:
#filling data with random value from normal distribution
a = np.random.normal() #by defualt mean = 0 and std = 1 and generates only 1 value
a

0.4967141530112327

In [3]:
a = np.random.normal(size=(3,5))
a #Don't run this cell twice it will change the values restart the kernel and start running from top if you have to.

array([[-0.1382643 ,  0.64768854,  1.52302986, -0.23415337, -0.23413696],
       [ 1.57921282,  0.76743473, -0.46947439,  0.54256004, -0.46341769],
       [-0.46572975,  0.24196227, -1.91328024, -1.72491783, -0.56228753]])

In [4]:
np.mean(a) #mean of all values

-0.060251587816810594

In [5]:
np.mean(a, axis=0) #mean along each column

array([ 0.32507292,  0.55236185, -0.28657492, -0.47217039, -0.41994739])

In [6]:
np.mean(a, axis=1) #mean along each row

array([ 0.31283275,  0.3912631 , -0.88485062])

In [9]:
#calculate var along axis 0 and std along axis 1
var_along_columns = #fill this one out
std_along_rows = #Fill this one out

SyntaxError: invalid syntax (<ipython-input-9-c5d4e34571b9>, line 2)

In [10]:
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
np.sum(a) #sum all elemebts by default
#How to find some along different axis?

#Is sum along third axis possible in this scenerio

21

In [13]:
np.prod(a) #Multiplies all elements together
#How to find prod along particular axis?


720

In [15]:
np.cumsum(a) #This is cumulative sum it doesn't add everything it adds the previous sum into the next element
#1 = 1
#1+2 = 3
#3+3 = 6
#....

array([ 1,  3,  6, 10, 15, 21])

In [19]:
np.cumsum(a, axis=1) #cumsum along the rows

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [20]:
np.cumprod(a) #No surprise here what it will do?

array([  1,   2,   6,  24, 120, 720])

In [21]:
np.max(a) #Find the max value in numpy array a

6

In [22]:
np.min(a) #Find's the minimum value

1

In [23]:
#By now you can easily figure out how to find max min value along particular dimensions 

In [26]:
#argmax and argmin
b = np.array([5,3,6,7,8,2])
np.argmax(b) #returns index of biggest element

4

In [27]:
b[np.argmax(b)] #you can see if we put that index in b it gives us biggest element

8

In [29]:
#figure out how to find the smallest element's index and smallest element
#Use this cell