In [1]:
import numpy as np

# Creating Numpy Arrays
| Function | Array Generated |
| -------- | --------------- |
| np.cos | Creates an array array with trignometric cosine of all elements in array. |
| np.round | Creates an array with all array elements being rounded off , having same type as input. |
| np.exp | Creates an array with exponential of all elements of input array. |
| np.log | Creates an array with Natural logarithmic value of all elements of input array. |
| np.power | Creates an array with elements of arr1 raised to exponential in arr2 .
| np.reminder | Creates an array with element wise remainder i.e arr1%arr2|
| np.reciprocal | Creates an array with reciprocal of all elements of input array. |
| np.abs| Creates an array with absolute value of each element of input array. |
| np.ceil | Creates an array of ceiling value with float datatype for each element.|
| np.floor | Create an array of floor value with float datatype for each element . |


In [3]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [4]:
a

array([[1, 2],
       [3, 4]])

In [5]:
b

array([[5, 6],
       [7, 8]])

In [6]:
a + b

array([[ 6,  8],
       [10, 12]])

In [7]:
a - b

array([[-4, -4],
       [-4, -4]])

In [8]:
a * b #Not matrix multiplication it's element wise multiplication

array([[ 5, 12],
       [21, 32]])

In [9]:
a / b  #element wise divide as matrix divide doesn't exist

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [10]:
a ** 2 #Case 1 

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [11]:
2 ** a #Case 2

array([[ 2,  4],
       [ 8, 16]], dtype=int32)

In [12]:
#What's the difference between case 1 and case 2?

In [13]:
a = np.array([4,5,6,7])
b = np.array([[1,2]])
print(a.shape)
print(b.shape)

(4,)
(1, 2)


In [25]:
a/ b 
#results into error try to understand what the error reflects.
#basically it says that you have different shapes and the operation you are trying cannot take place on these shapes

ValueError: operands could not be broadcast together with shapes (5,) (1,2) 

In [ ]:
a * b #not possible

In [ ]:
#shapes plays a very important role in numpy, you can try to do this calculate in mind and you will see it doesn't make sense

In [ ]:
"""Numpy Mathematical Functions"""

In [19]:
a = np.array([0,0.5,1,1.5,2])
cos_a = np.cos(np.pi * a) #It takes the values (here a ) in radians
cos_a #Let's round it

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

In [20]:
np.round(cos_a , decimals=4) #

array([ 1.,  0., -1., -0.,  1.])

In [ ]:
#exponential function e ** x
exp_a = np.exp(a) #equals e ** a
exp_a

In [16]:
#Log function default e, base of 2 and 10 can be used 
log_e = np.log(a)
log_2 = np.log2(a)
log_10 = np.log10(a)
print(log_e)
print(log_2)
print(log_10)
#Warnings shows that zero should be present when finding log as it's not allowed. but log handles 0 with 0

[1.38629436 1.60943791 1.79175947 1.94591015]
[2.         2.32192809 2.5849625  2.80735492]
[0.60205999 0.69897    0.77815125 0.84509804]


In [17]:
#Some more element wise mathematical functions 
a = np.array([[10,20,30],[70,80,90]])

In [18]:
np.power(a,2)

array([[ 100,  400,  900],
       [4900, 6400, 8100]], dtype=int32)

In [40]:
np.remainder(a,3) #Gives remainder after dividing with number

array([[1, 2, 0],
       [1, 2, 0]])

In [41]:
np.reciprocal(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
a = np.array([-1.2,2.3,-3.4])

In [45]:
np.abs(a)

array([1.2, 2.3, 3.4])

In [49]:
np.ceil(a) #rounds to then nearest greater integer

array([-1.,  3., -3.])

In [51]:
np.floor(a) #rounds to the nearest smallest integer

array([-2.,  2., -4.])

In [52]:
np.round(a) #just rounds

array([-1.,  2., -3.])