In [1]:
import numpy as np

In [2]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [3]:
a

array([[1, 2],
       [3, 4]])

In [4]:
b

array([[5, 6],
       [7, 8]])

In [5]:
a + b

array([[ 6,  8],
       [10, 12]])

In [6]:
a - b

array([[-4, -4],
       [-4, -4]])

In [7]:
a * b #Not matrix multiplication it's element wise multiplication

array([[ 5, 12],
       [21, 32]])

In [9]:
a / b  #element wise divide as matrix divide doesn't exist

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [11]:
a ** 2 #Case 1 

array([[ 1,  4],
       [ 9, 16]])

In [12]:
2 ** a #Case 2

array([[ 2,  4],
       [ 8, 16]])

In [13]:
#What's the difference between case 1 and case 2?

In [14]:
a = np.array([4,5,6,7])
b = np.array([[1,2]])
print(a.shape)
print(b.shape)

(4,)
(1, 2)


In [16]:
a / b 
#results into error try to understand what the error reflects.
#basically it says that you have different shapes and the operation you are trying cannot take place on these shapes

ValueError: operands could not be broadcast together with shapes (4,) (1,2) 

In [17]:
a * b #not possible

ValueError: operands could not be broadcast together with shapes (4,) (1,2) 

In [18]:
#shapes plays a very important role in numpy, you can try to do this calculate in mind and you will see it doesn't make sense

In [19]:
"""Numpy Mathematical Functions"""

'Numpy Mathematical Functions'

In [27]:
a = np.array([0,0.5,1,1.5,2])
cos_a = np.cos(np.pi * a) #It takes the values (here a ) in radians
cos_a #Let's round it

array([ 1.0000000e+00,  6.1232340e-17, -1.0000000e+00, -1.8369702e-16,
        1.0000000e+00])

In [28]:
np.round(cos_a , decimals=4) #

array([ 1.,  0., -1., -0.,  1.])

In [29]:
#exponential function e ** x
exp_a = np.exp(a) #equals e ** a
exp_a

array([1.        , 1.64872127, 2.71828183, 4.48168907, 7.3890561 ])

In [31]:
#Log function default e, base of 2 and 10 can be used 
log_e = np.log(a)
log_2 = np.log2(a)
log_10 = np.log10(a)
print(log_e)
print(log_2)
print(log_10)
#Warnings shows that zero should be present when finding log as it's not allowed. but log handles 0 with 0

[       -inf -0.69314718  0.          0.40546511  0.69314718]
[      -inf -1.         0.         0.5849625  1.       ]
[       -inf -0.30103     0.          0.17609126  0.30103   ]


/home/chirag/.local/lib/python3.6/site-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  
/home/chirag/.local/lib/python3.6/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in log2
  This is separate from the ipykernel package so we can avoid doing imports until
/home/chirag/.local/lib/python3.6/site-packages/ipykernel_launcher.py:4: RuntimeWarning: divide by zero encountered in log10
  after removing the cwd from sys.path.


In [38]:
#Some more element wise mathematical functions 
a = np.array([[10,20,30],[70,80,90]])

In [39]:
np.power(a,2)

array([[ 100,  400,  900],
       [4900, 6400, 8100]])

In [40]:
np.remainder(a,3) #Gives remainder after dividing with number

array([[1, 2, 0],
       [1, 2, 0]])

In [41]:
np.reciprocal(a)

array([[0, 0, 0],
       [0, 0, 0]])

In [44]:
a = np.array([-1.2,2.3,-3.4])

In [45]:
np.abs(a)

array([1.2, 2.3, 3.4])

In [49]:
np.ceil(a) #rounds to then nearest greater integer

array([-1.,  3., -3.])

In [51]:
np.floor(a) #rounds to the nearest smallest integer

array([-2.,  2., -4.])

In [52]:
np.round(a) #just rounds

array([-1.,  2., -3.])