In [2]:
import numpy as np

# Creating Numpy Arrays
| Function | Array Generated |
| -------- | --------------- |
| np.array | Creates an array for which the elements are given by an array-like object, which, for example, can be a (nested) Python list, a tuple, an iterable sequence, or another ndarray instance. |
| np.zeros | Creates an array with the specified dimensions and data type that is filled with zeros. np.ones Creates an array with the specified dimensions and data type that is filled with ones. |
| np.diag | Creates a diagonal array with specified values along the diagonal and zeros elsewhere. |
| np.arange | Creates an array with evenly spaced values between the specified start,  end, and increment values. |
| np.linspace | Creates an array with evenly spaced values between specified start and end values, using a specified number of elements.
| np.logspace | Creates an array with values that are logarithmically spaced between the given start and end values.|
| np.meshgrid | Generates coordinate matrices (and higher-dimensional coordinate arrays) from one-dimensional coordinate vectors. |
| np.fromfunction | Creates an array and fills it with values specified by a given function, which is evaluated for each combination of indices for the given array size. |
| np.fromfile | Creates an array with the data from a binary (or text) file. NumPy also provides a corresponding function np.tofile with which NumPy arrays can be stored to disk and later read back using np.fromfile.|
| np.genfromtxt,np.loadtxt | Create an array from data read from a text file, for example, a comma- loadtxt separated value (CSV) file. The function np.genfromtxt also supports data files with missing values. |
| np.random.rand | Generates an array with random numbers that are uniformly distributed between 0 and 1. Other types of distributions are also available in the np.random module. |

In [7]:
#Numpy Array From List or Interables
ary = np.array([1,2,3])
ary
print(ary.ndim) #Prints number of dimensions
print(ary.shape) #Prints the shape of array 

1
(3,)


In [12]:
#Other Iterables
x = range(10)
np_x = np.array(x)
np_x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [23]:
phone_dict = {1:'a', 2:'b', 3:'c'}
np_key = np.array(list(phone_dict.keys()))
np_value = np.array(list(phone_dict.values()))

In [24]:
np_key #It saves keys of dict as object by default

array([1, 2, 3])

In [25]:
np_value

array(['a', 'b', 'c'], dtype='<U1')

In [26]:
#What if I don't write type cast dict keys or values to list?
phone_dict = {1:'a', 2:'b', 3:'c'}
np_key = np.array(phone_dict.keys())
np_value = np.array(phone_dict.values())

In [27]:
np_key

array(dict_keys([1, 2, 3]), dtype=object)

In [28]:
np_value

array(dict_values(['a', 'b', 'c']), dtype=object)

In [32]:
try :
    print(np_key[0]) #Cannot access the value
except Exception as e:
    print(e)
    
try :
    print(np_value[0]) #Cannot access the value
except Exception as e:
    print(e)

too many indices for array
too many indices for array


In [34]:
#More than 1 dimensions
array_2d = [[1,2,3],[4,5,6],[7,8,9]]
numpy_2d = np.array(array_2d)
numpy_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [37]:
print("Dimensions in numpy_2d: ", numpy_2d.ndim)
print("Shape of numpy_2d: ", numpy_2d.shape) #3 rows X 3 columns

Dimensions in numpy_2d:  2
Shape of numpy_2d:  (3, 3)


In [38]:
#Array already filled with some values

In [49]:
#Array filled with zeros

In [46]:
matrix_3by4 = np.zeros((3,4)) #Can take 3 params shape,dtype and order
#shape takes the number of rows by number of columns in argument which will be default for all operations
#dtypes takes where you want this array to be of int type float type or with different capacities such as int32 or int64 as well.
#order means whether the array will be stored as row major or column major. Doesn't make much of difference in Python, by default is row major
#it makes difference for low level language connections for C or Fortran
print(matrix_3by4.dtype)
matrix_3by4

float64


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [48]:
matrix_3by4 = np.zeros((3,4), dtype=np.int32) 
#it makes difference for low level language connections for C or Fortran
print(matrix_3by4.dtype)
matrix_3by4 #See no decimal in the end

int32


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int32)

In [50]:
#Array filled with ones

In [51]:
matrix_2by3 = np.ones((2,3))
matrix_2by3

array([[1., 1., 1.],
       [1., 1., 1.]])

In [52]:
#In case you want to fill it with other constant
matrix_2by3 = np.ones((2,3)) * 5
matrix_2by3

array([[5., 5., 5.],
       [5., 5., 5.]])

In [54]:
#Another way of doing this is using np.full
matrix_4by4 = np.full((4,4), fill_value=5)
matrix_4by4

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [57]:
#What if I don't want any value in the array? Can i still create it?
matrix_3by3 = np.empty((3,3))
matrix_3by3 
#Why it's all 0?
#Empty array doesn't mean that your array will be empty
#It means unlike np.zeros they wont be intialized to 0 first

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
#Array with useful sequences

In [63]:
#arange

In [64]:
one_ten = np.arange(start=0, stop=10, step=1) #can take upto four arguments behaves similar to range in python 
one_ten

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
even = np.arange(start=0,stop=11,step=2)
even

array([ 0,  2,  4,  6,  8, 10])

In [66]:
#linspace

In [70]:
one_ten = np.linspace(start=0,stop=10,num=11) #gives equally distant points between your start and stop
one_ten

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [75]:
frac = np.linspace(start=0,stop=1,num=3)
frac #3 equally spaced points

array([0. , 0.5, 1. ])

In [76]:
#So what's the difference?
#arange gives you integer in every case but linspace gives equally spaced points which can be floating point.
#stop is not in arange while linspace stop is in resulting array

In [77]:
#Something for log

In [79]:
log_val = np.logspace(start=2,stop=5, num=4) #retuns evenly space values on log scale base by default = 10
log_val #They don't seem equally space as like this but convert them to log scale and you will see

array([   100.,   1000.,  10000., 100000.])

In [82]:
np.log10(log_val) #on log scale they are equally spaced values.

array([2., 3., 4., 5.])

In [84]:
#meshgrid

In [85]:
x,y = np.arange(2),np.arange(3)
print(x)
print(y)

[0 1]
[0 1 2]


In [88]:
co_x, co_y  = np.meshgrid(x,y) #Created co-ordinated matrics from co-ordinate system

In [89]:
co_x

array([[0, 1],
       [0, 1],
       [0, 1]])

In [90]:
co_y

array([[0, 0],
       [1, 1],
       [2, 2]])

In [91]:
#co_x and co_y on each index represent all of the possible co-ordinates combinations present in x and y.

In [92]:
#Comparison based arrays

In [93]:
x = np.array([[1,2,3],[4,5,6]])

In [94]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
y = np.ones_like(x) #take an numpy array as argument and creates an array filled with one of this shape
y
#Similarly zeros_like,empty_like can be created

array([[1, 1, 1],
       [1, 1, 1]])

In [99]:
#Multi-D array

In [102]:
x_iden = np.identity(3) #Create a square matrix of passed rows and columns with primary diagonal as 1
x_iden

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [104]:
#What if I want to select my own diagonal
y_iden = np.eye(3)
y_iden #Default behaviour as np.identity

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [106]:
y_iden = np.eye(3 , k=1)
y_iden

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [107]:
y_iden = np.eye(3 , k=-1)
y_iden

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [109]:
y_iden = np.eye(3, M=4, k=1) #We can explicitly mention the number of columns as M
y_iden

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [110]:
y_iden = np.eye(4, M=3, k=-2) #We can explicitly mention the number of columns as M
y_iden

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [112]:
#Create this kind of matrix but not filled with same value on the diagonal
#Create 1-d array and feed it to the np.diag
z_iden = np.diag([1,2,3])
z_iden

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [113]:
#Create this kind of matrix but not filled with same value on the diagonal
#Create 1-d array and feed it to the np.diag
z_1d = np.arange(5,25,2)
z_iden = np.diag(z_1d)
z_iden

array([[ 5,  0,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  7,  0,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  9,  0,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0, 11,  0,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0, 13,  0,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0, 15,  0,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 17,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 19,  0,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0, 21,  0],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0, 23]])

In [114]:
#From a function

In [119]:
f = lambda n,m : n+m
f_array = np.fromfunction(f, (2,2))
f_array #So the value passed in n,m are the row index, column index

array([[0., 1.],
       [1., 2.]])

In [1]:
#Create a 3by6 matrix where each position is filled by the sum of squares of row and column numbers for each element.

In [125]:
#random values
#https://het.as.utexas.edu/HET/Software/Numpy/reference/routines.random.html
#a whole new world of it's own