In [2]:
import numpy as np

# Indexing and Slicing in Numpy

| Expression | Result |
|----|------|
| ```a[m]``` | Select element at index m, where m is an integer (start counting form 0). |
| ```a[-m]``` | Select the n th element from the end of the list, where n is an integer. The last element in the list is addressed as -1, the second to last element as –2, and so on. |
|```a[m:n]``` | Select elements with index starting at m and ending at n − 1 (m and n are integers). |
| ```a[:] or a[0:-1]``` | Select all elements in the given axis. |
| ```a[:n]``` | Select elements starting with index 0 and going up to index n − 1 (integer). |
| ```a[m:] or a[m:-1]``` | Select elements starting with index m (integer) and going up to the last element in the array. |
| ```a[m:n:p]``` | Select elements with index m through n (exclusive), with increment p. |
| ```a[::-1]``` | Select all the elements, in reverse order. |

In [3]:
a = np.arange(20) #By default starts with 0
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [6]:
a[0] #Selecting 0th index or 1st element. Indexing starts with 0 in python and other major languages too

0

In [7]:
a[-1] #-1 means last element

19

In [9]:
a[-3] #-3 means 3rd last element

17

In [12]:
a[2:10] #means select everything from index 2 to 10(excluded)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
a[4:-3] #means select everything from index 4 to 3rd last index

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [15]:
a[4:17] #same as above

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [16]:
#Explain why both are same?

In [18]:
a[3:] #if we don't mention the limit of slicing it select everything from starting index

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
a[3:-1] #we can do this but there will be different behaviour

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18])

In [20]:
#What's the difference can you spot it?

In [22]:
a[0:10:2] #the new argument 2 means the step you want to take while selecting indices 2 means 0 then 2 then 4 ....by default step is 1

array([0, 2, 4, 6, 8])

In [23]:
a[0::4] 

array([ 0,  4,  8, 12, 16])

In [24]:
#2D Arrays

In [26]:
a = np.array([[1,2],[3,4]])
a

array([[1, 2],
       [3, 4]])

In [28]:
a[0] #Has two elements at 0th index

array([1, 2])

In [29]:
a[1] #same

array([3, 4])

In [33]:
a[0][0] #1 is stored at 0th place in 0th place of "a" (0,0)

1

In [40]:
b = np.array([np.arange(5), np.arange(5,10), np.arange(10,15), np.arange(15,20)])
b

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [42]:
#Selecting first two rows
b[:2] #this means select two rows and all columns in them

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [43]:
b[:2,:2] #first two rows and value of first two columns in them

array([[0, 1],
       [5, 6]])

In [45]:
b[:,:1] #all rows and first column for them

array([[ 0],
       [ 5],
       [10],
       [15]])

In [49]:
#selecting 0,2 rows
b[[0,2]]

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14]])

In [50]:
#can you select 2,4 columns?

In [51]:
#select sub-matrix forming from 6 to 13 in the above matrix

In [52]:
#how make value of this sub-matrix to 0?

In [53]:
#Memory Optimization

In [70]:
a = np.array([np.arange(5),np.arange(20,25), np.arange(100,105)])
a

array([[  0,   1,   2,   3,   4],
       [ 20,  21,  22,  23,  24],
       [100, 101, 102, 103, 104]])

In [71]:
#selecting a sub matrix of first two rows and first two columns
b = a[:2,:2] 
b

array([[ 0,  1],
       [20, 21]])

In [72]:
b[:1] = 901 #Making first row b matrix 0

In [73]:
b

array([[901, 901],
       [ 20,  21]])

In [74]:
a

array([[901, 901,   2,   3,   4],
       [ 20,  21,  22,  23,  24],
       [100, 101, 102, 103, 104]])

In [75]:
#but it changed our one as well?
#why this happened?
#numpy default doesn't create copies when we assign a numpy variable to another it just creates references
#b was a reference to part of matrix "a". when b was changed automatically a was changed.
#how to avoid this?
# use copy function

In [77]:
a = np.array([np.arange(5),np.arange(20,25), np.arange(100,105)])
b = a[:2,:2].copy()
b

array([[ 0,  1],
       [20, 21]])

In [78]:
b[:1] = 901
b

array([[901, 901],
       [ 20,  21]])

In [80]:
a #No changes reflected

array([[  0,   1,   2,   3,   4],
       [ 20,  21,  22,  23,  24],
       [100, 101, 102, 103, 104]])

In [81]:
#Boolean Indexing

In [83]:
np_a = np.arange(0,30)
np_a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [85]:
np_a > 15 #only values greater than 15 will return true

array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [87]:
np_a[np_a > 15] #A smart and short way of selecting indices

array([16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [88]:
#Can you select all of the even numbers in the np_a?

In [89]:
#Can you select multiples of 5?

In [110]:
#Arrays selected with boolean indexing are not references they are independent arrays
a = np.array(np.arange(5,50,5))
a

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])

In [111]:
idx_to_select = [2,3,4]
a[idx_to_select] #selecting values at index 2,3 and 4

array([15, 20, 25])

In [112]:
b = a[idx_to_select]

In [113]:
b

array([15, 20, 25])

In [114]:
b[2] = 25+125
b

array([ 15,  20, 150])

In [116]:
a #No change reflected into a 

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45])