**Question 1 :** Create a 4x2 integer array from a range between 10 to 50 such that the difference between each element is 5 .
And print the attributes of array also.

In [28]:
# Solution --

import numpy 
array = numpy.arange(10,50,5)  # np.arrange will create a array of all value possible between 
                               #  range (10,50) and a distance of 5 . 

reshaped_array = array.reshape(4,2) # array,reshape will convert that array into given dimentions
reshaped_array

array([[10, 15],
       [20, 25],
       [30, 35],
       [40, 45]])

In [33]:
reshaped_array.shape # gives shape of array

(4, 2)

In [34]:
reshaped_array.ndim # gives dimensions of array

2

In [35]:
reshaped_array.itemsize # tells length of each element of array in bytes

4

**Question 2 :** From the given numpy array return array of odd rows and even columns .

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

In [36]:
# Solution 

sampleArray = numpy.array([[3 ,6, 9, 12], [15 ,18, 21, 24], 
[27 ,30, 33, 36], [39 ,42, 45, 48], [51 ,54, 57, 60]])

newArray = sampleArray[::2 , 1::2] #  '::2' tells the row to be choosen and '1::2' is used for colunm
newArray

array([[ 6, 12],
       [30, 36],
       [54, 60]])

**Question 3 :** Split the array into four equal-sized sub-arrays


In [43]:
# Creating an array of size 8x3

sampleArray = numpy.arange(10,34,1)
reshapedArray = sampleArray.reshape(8,3)
reshapedArray

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27],
       [28, 29, 30],
       [31, 32, 33]])

In [45]:
# Dividing 8x3 array into 4 sub arrays

subArrays = numpy.split(sampleArray , 4)
subArrays

[array([10, 11, 12, 13, 14, 15]),
 array([16, 17, 18, 19, 20, 21]),
 array([22, 23, 24, 25, 26, 27]),
 array([28, 29, 30, 31, 32, 33])]

**Question 4 :** Write the code to convert the values of Centigrade degrees into Fahrenheit degrees. Centigrade values are stored into a NumPy array.

In [49]:
fvalues = [0, 12, 45.12, 34, 99.91] # list of values for which we want to calculate Centigrate degrees
fvalue_array = numpy.array(fvalues) # convering list inot numpy array
cel_values = 5*fvalue_array - 5*32/9  # formula for cinverting fahrenheit degrees into Centigrate degrees
cel_values

array([-17.77777778,  42.22222222, 207.82222222, 152.22222222,
       481.77222222])

**Question 5 :** Write the code to get the unique elements of an array.

In [50]:
x = [10,10,20,20,30,30] # list of values

x_array = numpy.array(x)

unique = numpy.unique(x_array) # using this function of numpy we can directly find out the unique values
unique

array([10, 20, 30])

In [51]:
# checking unique values in list of lists
x = [[1,3],[2,3]]
x_array = numpy.array(x)
unique = numpy.unique(x_array)
unique

array([1, 2, 3])

**Question 6 :** From the given 2-D array. Print max from axis 0 and min from axis 1

sample_array = [[34,43,73],[82,22,12],[53,94,66]]

In [53]:
sample_array = numpy.array([[34,43,73],[82,22,12],[53,94,66]])

min_of_axis_one = numpy.amin(sample_array, 1) # .amin() function calculates the min value from the axis
min_of_axis_one

array([34, 12, 53])

In [54]:
max_of_axis_one = numpy.amax(sample_array, 0) # .amax() function calculates the max value from the axis
max_of_axis_one

array([82, 94, 73])

**Question 7 :** From the given Numpy array delete column two and insert new column in its place.

sample_array = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

In [61]:
sample_array = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 

sample_array = numpy.delete(sample_array , 1, axis = 1) 
# numpy.delete function is used to deleting values from the array
# sameple_array is the array from which we want to delete
# '1' is the column number  [indexing of column and rows starts with 0]
# axis =1 means that we want to perform this action vertically or we can say column wise
sample_array

array([[34, 73],
       [82, 12],
       [53, 66]])

In [62]:
arr = numpy.array([[10,10,10]])

sample_array = numpy.insert(sample_array , 1 , arr , axis = 1)
# numpy.insert is used to insert any values in array
# all parameters are same as numpy.delete except 'arr' which is used for array that we want to insert
sample_array

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

**Question 8 :** Sort the given array along the first axis  and last axis .

sample_array = numpy.array([[10,40],[30,20]])

In [63]:
sample_array = numpy.array([[10,40],[30,20]])

sort_first = numpy.sort(sample_array , axis=0) # .sort function is used to sort the passed array 
                                                # and axis = 0 mean that we want to do it along first axis 
                                                # or we can say horizontally
sort_first

array([[10, 20],
       [30, 40]])

In [65]:
sort_last = numpy.sort(sample_array , axis =1) # here axis = 1 mean that we want to perform operation 
                                               # vertically or last axis
sort_last

array([[10, 40],
       [20, 30]])