## Reshaping and Reindexing

| Function | Result |
| -------- | ------ |
| ```np.reshape``` | Reshape an N-dimensional array. The total number of elements must remain the same. 
| ```np.flatten``` | Creates a copy of an N-dimensional array, and reinterpret it as a one-dimensional array (i.e., all dimensions are collapsed into one).|
| ```np.ravel``` | Create a view (if possible, otherwise a copy) of an N-dimensional array in which it is interpreted as a one-dimensional array.|
| ```np.squeeze``` | Removes axes with length 1.|
| ```np.expand_dims``` | Add a new axis (dimension) of length 1 to an array, where np.newaxis is used with array indexing.|
| ```np.transpose``` | Transpose the array. The transpose operation corresponds to reversing (or more generally, permuting) the axes of the array.|
| ```np.hstack``` | Stacks a list of arrays horizontally (along axis 1): for example, given a list of column vectors, appends the columns to form a matrix.|
| ```np.vstack``` | Stacks a list of arrays vertically (along axis 0): for example, given a list of row vectors, appends the rows to form a matrix.|
| ```np.dstack``` | Stacks arrays depth-wise (along axis 2).|
| ```np.concatenate``` | Creates a new array by appending arrays after each other, along a given axis.|
| ```np.resize``` | Resizes an array. Creates a new copy of the original array, with the requested size. If necessary, the original array will be repeated to fill up the new array.|
| ```np.append``` | Appends an element to an array. Creates a new copy of the array.|
| ```np.insert``` | Inserts a new element at a given position. Creates a new copy of the array.|
| ```np.delete``` | Deletes an element at a given position. Creates a new copy of the array.|

In [2]:
import numpy as np

In [3]:
digits = np.array([[1,2,3],[4,5,6]])
digits #original shape 2 rows 3 columns

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
digits.reshape((3,2)) #changing to 3 rows and 2 columns

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
digits.reshape((1,6)) #changing to 1 row 6 columns

array([[1, 2, 3, 4, 5, 6]])

In [8]:
digits.reshape((6,1)) #changing to 6 rows 1 column

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [9]:
#Make sure the product of dimensions in reshape is always equal to the product of original dimensions otherwise won't work

In [11]:
#To save the new dimensions either store them into another array or overwrite them on same array
digits = digits.reshape((3,2))
digits

array([[1, 2],
       [3, 4],
       [5, 6]])

In [12]:
#ravel and flatten
digits.flatten()

array([1, 2, 3, 4, 5, 6])

In [14]:
digits.ravel()

array([1, 2, 3, 4, 5, 6])

In [15]:
#Google out the difference between the ravel and flatten and create some cells here to show the difference.

In [16]:
digits_2d = np.array([[1,2,3],[3,4,5]])
digits_2d.shape

(2, 3)

In [30]:
digits_3d = np.expand_dims(digits_2d,axis=0)
digits_3d.shape #Added a new dimension on the 0th axis

(1, 2, 3)

In [31]:
digits_3d

array([[[1, 2, 3],
        [3, 4, 5]]])

In [32]:
digits_3d[0]

array([[1, 2, 3],
       [3, 4, 5]])

In [33]:
digits_3d = np.expand_dims(digits_2d,axis=1)
digits_3d.shape #Added a new dimension on the 1th axis

(2, 1, 3)

In [34]:
digits_3d

array([[[1, 2, 3]],

       [[3, 4, 5]]])

In [35]:
digits_3d[0]

array([[1, 2, 3]])

In [36]:
nums = np.array([[1,2,3,4],[5,6,7,8]])
nums

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [37]:
np.transpose(nums) #Changes dimensions with each other

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [39]:
nums.T #generates similar effect as np.transpose

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [41]:
array_1 = np.array([1,2,3,4,5])
array_2 = np.array([6,7,8,9,0])
np.hstack((array_1,array_2)) #horizontally attaches arrays

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [42]:
np.vstack((array_1,array_2))

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [43]:
np.dstack((array_1,array_2)) #Merges element to element

array([[[1, 6],
        [2, 7],
        [3, 8],
        [4, 9],
        [5, 0]]])

In [44]:
np.concatenate((array_1,array_2)) #by default axis = 0

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [47]:
try:
    np.concatenate((array_1,array_2), axis=1)
except Exception as e:
    print(e) 
#Expected behaviour since both arrays are 1D array, vstack is helful function in these scenerios

axis 1 is out of bounds for array of dimension 1


In [48]:
array_1 

array([1, 2, 3, 4, 5])

In [51]:
array_1_new = np.resize(array_1, new_shape=10) #this creates a new array with the mentioned size, the previous array is repeated
#to fill the values
array_1_new

array([1, 2, 3, 4, 5, 1, 2, 3, 4, 5])

In [52]:
array_1_new = np.resize(array_1, new_shape=4) 
array_1_new

array([1, 2, 3, 4])

In [53]:
array_1_new = np.resize(array_1, new_shape=(10,10)) 
array_1_new

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [55]:
array_1
np.append(array_1,6)

array([1, 2, 3, 4, 5, 6])

In [56]:
exp = np.array([np.arange(5),np.arange(5),np.arange(5)])
exp

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [62]:
#Figure out append,insert and delete and use the cells below to make your point.